// data.js - Comprehensive GATE Cutoff Data for All IITs & NITs
const institutesData = {
  iits: {
    core: [
      // Top Tier IITs (Top 7)
      {
        name: "IIT Bombay",
        branch: "Computer Science",
        qualify: 29.2,
        admission: 78.7,
        seats: 199,
        demand: "Very High",
      },
      {
        name: "IIT Bombay",
        branch: "Electrical Engineering",
        qualify: 25.0,
        admission: 72.5,
        seats: 180,
        demand: "High",
      },
      {
        name: "IIT Delhi",
        branch: "Mechanical Engineering",
        qualify: 35.8,
        admission: 65.2,
        seats: 175,
        demand: "High",
      },
      {
        name: "IIT Madras",
        branch: "Civil Engineering",
        qualify: 32.4,
        admission: 62.8,
        seats: 160,
        demand: "Medium",
      },
      {
        name: "IIT Kanpur",
        branch: "Aerospace Engineering",
        qualify: 28.7,
        admission: 68.3,
        seats: 85,
        demand: "High",
      },
      {
        name: "IIT Kharagpur",
        branch: "Chemical Engineering",
        qualify: 31.5,
        admission: 64.2,
        seats: 155,
        demand: "Medium",
      },
      {
        name: "IIT Roorkee",
        branch: "Metallurgical Engineering",
        qualify: 26.8,
        admission: 58.9,
        seats: 110,
        demand: "Medium",
      },

      // Mid Tier IITs (8-15)
      {
        name: "IIT Guwahati",
        branch: "Civil Engineering",
        qualify: 28.3,
        admission: 60.7,
        seats: 120,
        demand: "Medium",
      },
      {
        name: "IIT Hyderabad",
        branch: "Mechanical Engineering",
        qualify: 27.9,
        admission: 61.2,
        seats: 130,
        demand: "Medium",
      },
      {
        name: "IIT (BHU) Varanasi",
        branch: "Ceramic Engineering",
        qualify: 25.2,
        admission: 55.8,
        seats: 84,
        demand: "Medium",
      },
      {
        name: "IIT Dhanbad",
        branch: "Mining Engineering",
        qualify: 24.8,
        admission: 53.7,
        seats: 90,
        demand: "Medium",
      },
      {
        name: "IIT Indore",
        branch: "Electrical Engineering",
        qualify: 26.5,
        admission: 59.3,
        seats: 95,
        demand: "Medium",
      },
      {
        name: "IIT Mandi",
        branch: "Civil Engineering",
        qualify: 25.7,
        admission: 56.2,
        seats: 85,
        demand: "Medium",
      },

      // Newer IITs (16-23)
      {
        name: "IIT Palakkad",
        branch: "Computer Science",
        qualify: 28.5,
        admission: 63.7,
        seats: 60,
        demand: "Medium",
      },
      {
        name: "IIT Tirupati",
        branch: "Electrical Engineering",
        qualify: 24.2,
        admission: 52.8,
        seats: 65,
        demand: "Medium",
      },
      {
        name: "IIT Jammu",
        branch: "Mechanical Engineering",
        qualify: 23.8,
        admission: 51.3,
        seats: 70,
        demand: "Medium",
      },
      {
        name: "IIT Dharwad",
        branch: "Civil Engineering",
        qualify: 22.7,
        admission: 49.6,
        seats: 55,
        demand: "Medium",
      },
      {
        name: "IIT Bhilai",
        branch: "Computer Science",
        qualify: 26.3,
        admission: 58.4,
        seats: 48,
        demand: "Medium",
      },
      {
        name: "IIT Goa",
        branch: "Electrical Engineering",
        qualify: 24.9,
        admission: 53.7,
        seats: 40,
        demand: "Medium",
      },
      {
        name: "IIT Bhubaneswar",
        branch: "Mechanical Engineering",
        qualify: 25.4,
        admission: 54.9,
        seats: 90,
        demand: "Medium",
      },
    ],
    emerging: [
      // AI/Data Science Programs
      {
        name: "IIT Hyderabad",
        branch: "Artificial Intelligence",
        qualify: 29.0,
        admission: 77.1,
        seats: 65,
        growth: "Rapid",
      },
      {
        name: "IIT Kharagpur",
        branch: "Data Science & AI",
        qualify: 29.0,
        admission: 76.5,
        seats: 70,
        growth: "High",
      },
      {
        name: "IIT Madras",
        branch: "AI & Robotics",
        qualify: 28.8,
        admission: 75.8,
        seats: 60,
        growth: "High",
      },
      {
        name: "IIT Roorkee",
        branch: "Data Science & Engineering",
        qualify: 28.5,
        admission: 74.3,
        seats: 55,
        growth: "High",
      },
      {
        name: "IIT Kanpur",
        branch: "Cyber Security",
        qualify: 28.2,
        admission: 73.6,
        seats: 50,
        growth: "Medium",
      },
      {
        name: "IIT Delhi",
        branch: "Machine Learning",
        qualify: 29.1,
        admission: 76.8,
        seats: 60,
        growth: "Rapid",
      },

      // Energy & Sustainability
      {
        name: "IIT Bombay",
        branch: "Energy Engineering",
        qualify: 27.5,
        admission: 68.2,
        seats: 50,
        growth: "High",
      },
      {
        name: "IIT Delhi",
        branch: "Renewable Energy Systems",
        qualify: 27.3,
        admission: 67.5,
        seats: 45,
        growth: "High",
      },
    ],
    interdisciplinary: [
      // Healthcare Technology
      {
        name: "IIT Madras",
        branch: "Instrumentation & Biomedical Engineering",
        qualify: 26.6,
        admission: 58.7,
        seats: 40,
        field: "Healthcare",
      },
      {
        name: "IIT Bombay",
        branch: "Biotechnology",
        qualify: 25.8,
        admission: 56.3,
        seats: 45,
        field: "Biotech",
      },

      // Computational Engineering
      {
        name: "IIT Madras",
        branch: "Computational Engineering & Mechanics",
        qualify: 27.2,
        admission: 60.8,
        seats: 35,
        field: "Engineering",
      },
      {
        name: "IIT Kanpur",
        branch: "Materials Science",
        qualify: 25.4,
        admission: 54.7,
        seats: 40,
        field: "Materials",
      },

      // Environmental & Infrastructure
      {
        name: "IIT Delhi",
        branch: "Environmental Science & Engineering",
        qualify: 26.1,
        admission: 55.2,
        seats: 50,
        field: "Environment",
      },
      {
        name: "IIT Jodhpur",
        branch: "Civil & Infrastructure Engineering",
        qualify: 24.7,
        admission: 52.3,
        seats: 55,
        field: "Infrastructure",
      },
      {
        name: "IIT Dharwad",
        branch: "Water Resources Engineering",
        qualify: 23.5,
        admission: 49.8,
        seats: 40,
        field: "Environment",
      },

      // Agriculture & Industrial
      {
        name: "IIT Kharagpur",
        branch: "Agricultural Technology",
        qualify: 24.3,
        admission: 50.5,
        seats: 60,
        field: "Agriculture",
      },
      {
        name: "IIT Roorkee",
        branch: "Geo-informatics",
        qualify: 24.1,
        admission: 49.3,
        seats: 45,
        field: "Geospatial",
      },
      {
        name: "IIT Bhilai",
        branch: "Industrial Design",
        qualify: 23.8,
        admission: 48.7,
        seats: 35,
        field: "Design",
      },
    ],
  },
  nits: {
    core: [
      // Top NITs
      {
        name: "NIT Trichy",
        branch: "Mechanical Engineering",
        qualify: 25.8,
        admission: 63.2,
        seats: 120,
        demand: "High",
      },
      {
        name: "NIT Warangal",
        branch: "Electrical Engineering",
        qualify: 26.3,
        admission: 64.7,
        seats: 110,
        demand: "High",
      },
      {
        name: "NIT Surathkal",
        branch: "Chemical Engineering",
        qualify: 24.7,
        admission: 60.3,
        seats: 90,
        demand: "Medium",
      },
      {
        name: "NIT Calicut",
        branch: "Civil Engineering",
        qualify: 24.2,
        admission: 59.8,
        seats: 100,
        demand: "Medium",
      },

      // Mid Tier NITs
      {
        name: "NIT Rourkela",
        branch: "Metallurgical Engineering",
        qualify: 23.5,
        admission: 56.7,
        seats: 85,
        demand: "Medium",
      },
      {
        name: "NIT Durgapur",
        branch: "Chemical Engineering",
        qualify: 23.2,
        admission: 55.4,
        seats: 80,
        demand: "Medium",
      },
      {
        name: "NIT Allahabad",
        branch: "Mechanical Engineering",
        qualify: 25.2,
        admission: 61.8,
        seats: 95,
        demand: "Medium",
      },

      // Newer NITs
      {
        name: "NIT Silchar",
        branch: "Civil Engineering",
        qualify: 22.8,
        admission: 53.6,
        seats: 75,
        demand: "Medium",
      },
      {
        name: "NIT Nagpur",
        branch: "Electrical Engineering",
        qualify: 23.6,
        admission: 56.2,
        seats: 70,
        demand: "Medium",
      },
      {
        name: "NIT Meghalaya",
        branch: "Mechanical Engineering",
        qualify: 21.7,
        admission: 50.3,
        seats: 60,
        demand: "Medium",
      },
    ],
    cse: [
      {
        name: "NIT Trichy",
        branch: "Computer Science",
        qualify: 29.2,
        admission: 71.5,
        seats: 150,
        placement: "Excellent",
      },
      {
        name: "NIT Warangal",
        branch: "Computer Science",
        qualify: 28.7,
        admission: 70.8,
        seats: 140,
        placement: "Excellent",
      },
      {
        name: "NIT Surathkal",
        branch: "Information Technology",
        qualify: 28.5,
        admission: 69.7,
        seats: 130,
        placement: "Excellent",
      },
      {
        name: "NIT Calicut",
        branch: "AI & ML",
        qualify: 28.3,
        admission: 68.9,
        seats: 70,
        placement: "Excellent",
      },
      {
        name: "NIT Rourkela",
        branch: "Data Science",
        qualify: 27.8,
        admission: 67.5,
        seats: 65,
        placement: "Excellent",
      },
      {
        name: "NIT Allahabad",
        branch: "IT Security",
        qualify: 27.5,
        admission: 66.8,
        seats: 60,
        placement: "Excellent",
      },
    ],
    interdisciplinary: [
      {
        name: "NIT Trichy",
        branch: "Industrial Engineering",
        qualify: 24.5,
        admission: 57.3,
        seats: 60,
        field: "Industrial",
      },
      {
        name: "NIT Warangal",
        branch: "Material Science",
        qualify: 23.8,
        admission: 55.7,
        seats: 50,
        field: "Materials",
      },
      {
        name: "NIT Rourkela",
        branch: "Biomedical Engineering",
        qualify: 23.2,
        admission: 54.1,
        seats: 45,
        field: "Healthcare",
      },
      {
        name: "NIT Calicut",
        branch: "Environmental Engineering",
        qualify: 23.0,
        admission: 53.8,
        seats: 55,
        field: "Environment",
      },
      {
        name: "NIT Durgapur",
        branch: "Agricultural Engineering",
        qualify: 22.3,
        admission: 51.2,
        seats: 50,
        field: "Agriculture",
      },
      {
        name: "NIT Silchar",
        branch: "Water Resources Engineering",
        qualify: 21.5,
        admission: 49.7,
        seats: 40,
        field: "Environment",
      },
    ],
  },
};
